import Footer from '@/components/footer';
import Getstarted from '@/components/getstarted';
import Hero from '@/components/hero';
import NewNavbar from '@/components/newnav';
import Specialiy from '@/components/speciality';
import Tutorial from '@/components/tutorial';
import Styles from '../styles/defaultstyles';
import Image from 'next/image';
import backgroundvillage from '../public/background2.jpg';
import { motion } from 'framer-motion';

import Head from 'next/head';

const Index = () => {
  return (
    <>
      <Head>
        <title>NoSpam.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div exit={{ opacity: 0 }} initial={{ opacity: 0 }} animate={{ opacity: 4 }} className="">
        <div className={`${Styles.pxpadding} lg:px-28 px-6 pt-5 z-20 `}>
          <NewNavbar />
        </div>
        <div
          className={`${Styles.pxpadding} lg:px-28 px-6 bg-repeat `}
          style={{ backgroundImage: 'url(https://www.toptal.com/designers/subtlepatterns/uploads/dot-grid.png)' }}
        >
          <div className=" my-11 lg:my-0">
            <Hero />
          </div>
        </div>
        <div className={`${Styles.pxpadding} lg:px-28 px-6 bg-[#80FFDB] `}>
          <Tutorial />
        </div>
        <div
          className={`${Styles.pxpadding} lg:px-28 px-6 bg-repeat flex justify-center flex-col `}
          style={{ backgroundImage: 'url(https://www.toptal.com/designers/subtlepatterns/uploads/dot-grid.png)' }}
        >
          <div className="mt-20 lg:mb-10 mb-5 flex flex-col items-center">
            <Specialiy />
          </div>
          <div className=" flex flex-col items-center  z-10">
            <Getstarted />
          </div>
        </div>
        <div className="bg-[#122D42] mt-10 overflow-hidden relative">
          <div className={`${Styles.pxpadding} lg:px-28 px-6  flex flex-col `}>
            <div className="z-10">
              <Footer />
            </div>
            <Image
              src={backgroundvillage}
              alt="background"
              layout="fill"
              objectFit="cover"
              objectPosition="center"
              quality={100}
              className=" absolute object-center z-0 opacity-10"
            />
          </div>
        </div>
        <div className="w-screen h-2 bg-green-500"></div>
      </motion.div>
    </>
  );
};
export default Index;
