import Footer from '@/components/footer';
import Getstarted from '@/components/getstarted';
import Hero from '@/components/hero';
import Navbar from '@/components/navbar';
import Specialiy from '@/components/speciality';
import Tutorial from '@/components/tutorial';

import Head from 'next/head';

const Index = () => {
  return (
    <>
      <Head>
        <title>NoSpam.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Hero />
        <Tutorial />
        <Specialiy />
        <Getstarted />
        <Footer />
      </div>
    </>
  );
};
export default Index;
